<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/03/25 21:43:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
